//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Expense = newExpenseTable("public", "expense", "")

type expenseTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnInteger
	CreatedAt    postgres.ColumnTimestamp
	UpdatedAt    postgres.ColumnTimestamp
	UserID       postgres.ColumnString
	Amount       postgres.ColumnFloat
	PurchaseDate postgres.ColumnTimestamp
	BillDate     postgres.ColumnTimestamp
	Description  postgres.ColumnString
	CategoryID   postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ExpenseTable struct {
	expenseTable

	EXCLUDED expenseTable
}

// AS creates new ExpenseTable with assigned alias
func (a ExpenseTable) AS(alias string) *ExpenseTable {
	return newExpenseTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ExpenseTable with assigned schema name
func (a ExpenseTable) FromSchema(schemaName string) *ExpenseTable {
	return newExpenseTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ExpenseTable with assigned table prefix
func (a ExpenseTable) WithPrefix(prefix string) *ExpenseTable {
	return newExpenseTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ExpenseTable with assigned table suffix
func (a ExpenseTable) WithSuffix(suffix string) *ExpenseTable {
	return newExpenseTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newExpenseTable(schemaName, tableName, alias string) *ExpenseTable {
	return &ExpenseTable{
		expenseTable: newExpenseTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newExpenseTableImpl("", "excluded", ""),
	}
}

func newExpenseTableImpl(schemaName, tableName, alias string) expenseTable {
	var (
		IDColumn           = postgres.IntegerColumn("id")
		CreatedAtColumn    = postgres.TimestampColumn("created_at")
		UpdatedAtColumn    = postgres.TimestampColumn("updated_at")
		UserIDColumn       = postgres.StringColumn("user_id")
		AmountColumn       = postgres.FloatColumn("amount")
		PurchaseDateColumn = postgres.TimestampColumn("purchase_date")
		BillDateColumn     = postgres.TimestampColumn("bill_date")
		DescriptionColumn  = postgres.StringColumn("description")
		CategoryIDColumn   = postgres.IntegerColumn("category_id")
		allColumns         = postgres.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn, UserIDColumn, AmountColumn, PurchaseDateColumn, BillDateColumn, DescriptionColumn, CategoryIDColumn}
		mutableColumns     = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn, UserIDColumn, AmountColumn, PurchaseDateColumn, BillDateColumn, DescriptionColumn, CategoryIDColumn}
	)

	return expenseTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		CreatedAt:    CreatedAtColumn,
		UpdatedAt:    UpdatedAtColumn,
		UserID:       UserIDColumn,
		Amount:       AmountColumn,
		PurchaseDate: PurchaseDateColumn,
		BillDate:     BillDateColumn,
		Description:  DescriptionColumn,
		CategoryID:   CategoryIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
